---
nomad_version: 0.8.0
nomad_sha256sum:
  "0.8.0": 1166cc6cb8b8ef4af73c7ed745b938fd060c6a6222111c13ff5d88efbccd66c5
  "0.7.1": 72b32799c2128ed9d2bb6cbf00c7600644a8d06c521a320e42d5493a5d8a789a
nomad_user: nomad
nomad_group: nomad
nomad_tmp_dir: /tmp
nomad_install_dir: /usr/local/sbin
nomad_config_dir: /etc/nomad.d
nomad_config_file: nomad.hcl
nomad_data_dir: /var/lib/nomad
nomad_log_dir: /var/log/nomad

# sysconfig
nomad_sysconfig_dir: /etc/default
nomad_gomaxprocs: 2
nomad_options: "-server"

# nomad config
nomad_region: global
nomad_datacenter: dc1
nomad_bootstrap_expect: 3
nomad_server: false
nomad_servers: []
nomad_node_name: "{{ ansible_hostname }}"
nomad_bind_addr: "0.0.0.0"

nomad_port_http: 4646
nomad_port_rpc:  4647
nomad_port_serf: 4648

nomad_advertise_addr: "{{ ansible_default_ipv4.address }}"

nomad_log_level: INFO
nomad_enable_debug: false
nomad_enable_syslog: true
